name: Smart Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at 12:00 AM UTC (5 AM Pakistan Time)
  workflow_dispatch:  # Manually trigger karne ka option bhi

jobs:
  check-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if Any Commit Exists Today
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%Y-%m-%d')
          TODAY=$(date -u +"%Y-%m-%d")
          if [[ "$LAST_COMMIT_DATE" == "$TODAY" ]]; then
            echo "Already committed today. Skipping auto-commit."
            exit 0
          fi

      - name: Auto Commit (Only if No Commit Today)
        run: |
          date > last-updated.txt
          git config --global user.name "moiz-xyz"
          git config --global user.email "a.moizniaxi123@gmail.com"
          git add .
          git commit -m "Backup commit to maintain streak - $(date)"
          git push
